baseURL: "www.gesuindia.com" 
title: Gesu India
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    # main:
    #     - name: Books
    #       url: books/
    #       weight: 5 
    #     - name: Papers
    #       url: papers/
    #       weight: 2
    #     - name: Courses
    #       url: courses/
    #       weight: 3
    #     - name: Data
    #       url: data/
    #       weight: 4 
    #     - name: Blog
    #       url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
    #       weight: 6

params:
    description: "This website hosts research updates for Dr. Gesu India."
    author: Gesu India
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["cv"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Gesu India
          subtitle: "I am a computer scientist, particularly interested in human-computer interaction, responsible AI, and accessibility. I use mixed-methods in my research to cater to my endless fascination with how people and technologies continue to shape each other."


          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: cv.pdf

    socialIcons:
      # - name: CV
      #     url: cv.pdf
        - name: Email
          url: mailto:gesuindia@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=kdl-wLoAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/gesuindia
       # - name: LinkedIn
       #    url: https://www.linkedin.com/in/gesuindia/
        - name: Twitter
          url: https://x.com/GesuIndia
           

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gesu India"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2